import { Inter } from "next/font/google";



const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Adminlayout({ children }) {
  return (
    <main>
    <html lang="en">
      <body className={inter.className} >
        <div className=" relative flex-1 p-6">
        {children}</div>
      </body>
    </html>
    </main>
  );
}
     